"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$os$username$directory$git_branch$git_status$cmd_duration$time
$character
"""

[os]
disabled = false
style = "bold blue"
format = "[$symbol ]($style)"

[os.symbols]
Macos = "mac"
Linux = "linux"
Windows = "win"

[username]
show_always = false
style_user = "bold cyan"
style_root = "bold red"
format = "[$user]($style) "

[directory]
style = "bold green"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "../"

[git_branch]
symbol = "git:"
style = "bold yellow"
format = "[$symbol$branch]($style) "

[git_status]
style = "yellow"
format = "[$all_status$ahead_behind]($style) "
ahead = "↑${count}"
diverged = "⇕↑${ahead_count}↓${behind_count}"
behind = "↓${count}"

[cmd_duration]
show_milliseconds = false
format = "[$duration]($style) "
style = "bold magenta"
disabled = false

[time]
disabled = false
time_format = "%H:%M"
style = "bold white"
format = "[$time]($style) "

[character]
success_symbol = "> "
error_symbol = "!> "
