"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$directory$git_branch$git_status
$character
"""

[directory]
style = "bold green"
format = "[$path]($style) "
truncation_length = 2
truncation_symbol = "../"

[git_branch]
symbol = "git:"
style = "bold yellow"
format = "[$symbol$branch]($style) "

[git_status]
style = "yellow"
format = "[$all_status$ahead_behind]($style) "
ahead = "↑${count}"
diverged = "⇕↑${ahead_count}↓${behind_count}"
behind = "↓${count}"

[character]
success_symbol = "> "
error_symbol = "!> "
